js/build.js
ref https://github.com/Fliplet/fliplet-studio/issues/1750
=> Rely on session to redirect instead of local storage

build.html, js/build.js, js/interface.js
This reverts commit ef158cb76650c0a73236058cdcacbccf87aaf761, reversing
changes made to 9bc3130f2bee64c8214ed55229ba929b0a36878c.
=> Revert "Merge pull request #9 from Fliplet/fix/prevent-no-configutarion"

js/build.js
Corrected additional references to 'authenticate' and 'authenticating...' that were being passed through
=> Corrected additional references

build.html
For https://github.com/Fliplet/fliplet-studio/issues/2109
=> Fix: button inside form was submitting it

build.html, js/build.js
ref https://github.com/Fliplet/fliplet-studio/issues/2526
=> support for displaying error messages from apis

js/build.js
ref https://github.com/Fliplet/fliplet-studio/issues/2778
=> fix for ie11

js/build.js
This avoids using **Please enter a valid email** as the generic fallback error
=> Improves parsing of validation errors

js/build.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3253
=> Ensures widget is rendered and editable if the widget is not configured

css/interface.css, interface.html
@tonytlwu @squallstar 
**Fixed behavior**:
Created one tab from two tabs. Removed unnecessary classes etc.
ref https://github.com/Fliplet/fliplet-studio/issues/3207
=> Two tabs in one

interface.html
@tonytlwu @squallstar
Issue
Fliplet/fliplet-studio#4959
Description
Added link on "Need help" button.
Backward compatibility
=> Clicking on "Need help" now leads to Fliplet documentation about Verification

.eslintrc, .gitignore, js/build.js, js/interface.js, package-lock.json
@sofiiakvasnevska
Added es-lint.
=> Added es-lint

css/build.css, js/build.js
@sofiiakvasnevska 
https://github.com/Fliplet/fliplet-studio/issues/5354
Changed components so they work with Fliplet.Widget.instance now.
https://share.getcloudapp.com/Qwu7RnDj
=> User will not lose components when change they position in the new D&D

js/build.js
Added new JS API to set the verification email and request a code.
```js
Fliplet.Verification.Email.get().then(function (verification) {
verification.setEmail('foo@example.org');
verification.requestCode().then(console.log, console.error);
});
```
=> ID-701 [Feat] Added js api to access instance and set email

js/build.js
Will ask QA to do a full testing of the component after these changes.
All tested locally.
=> ID-701 [Chore] Refactored initialisation

build.html, js/build.js
Ref. https://weboo.atlassian.net/browse/ID-1072
=> ID-1072 [Feat] Show error messages as returned by API

js/build.js
Ref. https://weboo.atlassian.net/browse/ID-2109
=> ID-2109 [Fix] Fix login form position after changing state

.eslintrc, build.html, js/build.js, translation.json
@sofiiakvasnevska @inna-bieshulia
OD-579 https://weboo.atlassian.net/browse/OD-579
Added translations to the Email-verification component
@upplabs-alex-levchenko
=> OD-579 [Feature] Added translation to Widget-Email verification component

css/build.css
@romanyosyfiv @inna-bieshulia
OD-514 https://weboo.atlassian.net/browse/OD-514
@upplabs-alex-levchenko
This PR must be launched together with this https://github.com/Fliplet/fliplet-theme-default/pull/190 for correct work.
=> OD-514 [Fix] Update styles for theme settings to work correctly

build.html, js/build.js
@romanyosyfiv
OD-859 https://weboo.atlassian.net/browse/OD-859
Ref.https://github.com/Fliplet/fliplet-widget-chart-bar/pull/50
@upplabs-alex-levchenko
=> OD-859 [Fix] Fixed initialization for translation

css/build.css
Reverts Fliplet/fliplet-widget-email-verification#48
=> Revert "OD-514 [Fix] Update styles for theme settings to work correctly"

build.html, css/build.css, interface.html, js/build.js, translation.json
| PR | Merged by |
| -- | --------- |
| #49 OD-787 [Fix] Fixed title |  @OleksandrLavrynenko |
| #45 OD-579 [Feature] Added translation to Widget-Email verification component | @skrupnyk |
| #50 OD-859 [Fix] Fixed initialization for translation |  @OleksandrLavrynenko |
=> Release to Production

js/interface.js
Passes `isPublicApp` variable to validation manager provider
https://weboo.atlassian.net/browse/ID-4531
=> ID-4531 Pass variable to validation manager provider

css/build.css, js/interface.js
Passes `isPublicApp` variable to validation manager provider
https://weboo.atlassian.net/browse/ID-4531
=> Release 20240704
